apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
      matchLabels:
        app: myapp
        version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
        - name: myapp
          image: docker.io/vinceangway/blue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
    
