apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
      matchLabels:
        app: myapp
        version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp
          image: docker.io/vinceangway/green
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  
